micronaut:
  application:
    name: demo
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/noctuai
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema: demo
#--------------------------------------------------------------------#
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: true
#--------------------------------------------------------------------#
flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true
